# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
