# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-23 18:56
from __future__ import unicode_literals

import app.validators.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180123_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.IntegerField(unique=True, validators=[app.validators.phone.validate_size]),
        ),
    ]
