# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-24 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pricerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_price', models.DecimalField(decimal_places=2, max_digits=99)),
                ('call_end_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_call_end_records', to='app.CallEndRecord')),
                ('call_start_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_call_start_records', to='app.CallStartRecord')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_subscribers', to='app.Subscriber')),
            ],
        ),
        migrations.AlterField(
            model_name='pricerate',
            name='rate_type',
            field=models.CharField(choices=[('rdc', 'reduced'), ('std', 'standard')], max_length=3),
        ),
    ]
