# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-24 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180124_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billrecord',
            name='call_end_record',
        ),
        migrations.RemoveField(
            model_name='billrecord',
            name='call_start_record',
        ),
        migrations.AddField(
            model_name='billrecord',
            name='call_record',
            field=models.ForeignKey(db_column='call_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_call_records', to='app.CallStartRecord', to_field='call_id'),
        ),
        migrations.AlterField(
            model_name='pricerate',
            name='rate_type',
            field=models.CharField(choices=[('std', 'standard'), ('rdc', 'reduced')], max_length=3),
        ),
    ]
