# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-25 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180124_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerate',
            name='rate_type',
            field=models.CharField(choices=[('rdc', 'reduced'), ('std', 'standard')], max_length=3),
        ),
    ]
