# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-25 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180125_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricerate',
            old_name='end_datetime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='pricerate',
            old_name='start_datetime',
            new_name='start_time',
        ),
    ]
