# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-24 21:22
from __future__ import unicode_literals

import app.validators.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_callendrecord_callstartrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callendrecord',
            name='call_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='call_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.IntegerField(db_index=True, unique=True, validators=[app.validators.phone.validate_size]),
        ),
    ]
