# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-24 21:31
from __future__ import unicode_literals

import app.validators.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180124_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstartrecord',
            name='destination_phone',
            field=models.BigIntegerField(validators=[app.validators.phone.validate_size]),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='origin_phone',
            field=models.BigIntegerField(validators=[app.validators.phone.validate_size]),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.BigIntegerField(db_index=True, unique=True, validators=[app.validators.phone.validate_size]),
        ),
    ]
