# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-25 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180125_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerate',
            name='rate_type',
            field=models.CharField(choices=[('std', 'standard'), ('rdc', 'reduced')], max_length=3),
        ),
    ]
